merchex/merchex/urls.py
from django.contrib import admin
from django.urls import path
from listings import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('bands/', views.band_list,name='band-list'),
    path('bands/<int:band_id>/', 
        views.band_detail, 
        name='band-detail'
    ), # ajouter ce motif sous notre autre motif de groupes

    path('bands/<int:id>/change/', views.band_update, name='band-update'),
    path('bands/add/', views.band_create, name='band-create'),
    path('bands/<int:id>/delete/', views.band_delete, name='band-delete'),
    path('listings/add/', views.listing_create, name='listing-create'),

    path('listings/', views.listing_list,name='listing-list'),
    path('listings/<int:listing_id>/',
        views.listing_detail, 
        name='listing-detail'
    ), # ajouter ce motif sous notre autre motif de groupes
    path('listings/<int:listing_an_id>/', 
        views.listing_detail_annonce, 
        name='listing-detail_annonce'
    ), # ajouter ce motif sous notre autre motif de groupes 
    path('contact-us/', views.contact, name="contact"),
    path('about-us/', views.about),
    path('', views.home),
]

merchex/listings/models.py
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator

class Band(models.Model):
    name = models.fields.CharField(max_length=100)
    class Genre(models.TextChoices):
        ZOUGLOU = 'ZG'
        COUPE_DECALE= 'CD'
        SPOT= 'SP'
    
    genre = models.fields.CharField(choices=Genre.choices, max_length=5)
    biography = models.fields.CharField(max_length=1000)
    year_formed = models.fields.PositiveIntegerField(
        validators=[MinValueValidator(1900), MaxValueValidator(2022)]
    )
    active = models.fields.BooleanField(default=True)
    official_homepage = models.fields.URLField(null=True, blank=True)
    #like_new = models.fields.BooleanField(default=False)
    def __str__(self):
        return f'{self.name}'


class Listing(models.Model):
    title = models.fields.CharField(max_length= 100)
    description =  models.fields.CharField(max_length= 100)
    class ListingType(models.TextChoices):
            RECORDS = 'R'#disques
            CLOTHINGS= 'C'# vetements
            POSTERS= 'P'
            MISCELLANEOUS ='MS' #Divers
    sold = models.fields.BooleanField(default=True)
    year = models.fields.PositiveIntegerField(
        validators=[MinValueValidator(1900), MaxValueValidator(2022)]
    )
    types = models.fields.CharField(choices=ListingType.choices, max_length=5)
    band = models.ForeignKey(Band, null=True, on_delete=models.SET_NULL)

    def __str__(self):
        return self.title

merchex/listings/forms.py
from django import forms
from listings.models import Band, Listing

class ContactUsForm(forms.Form):

    name = forms.CharField(required=False)
    email = forms.EmailField()
    message = forms.CharField(max_length=1000)

#le modelForm use le model pour lequel nous voulons créer une vue
class BandForm(forms.ModelForm):
    class Meta:
        model = Band #qui spécifie le modèle pour lequel ce formulaire sera utilisé
        #fields = '__all__' #les champs de ce modèle à inclure dans ce formulaire (ici tous)
        #exclu des champs d'un modelform
        exclude = ('active', 'official_homepage')  # ajoutez cette ligne

class ListingForm(forms.ModelForm):
    class Meta:
        model = Listing
        fields = '__all__'

merchex/listings/views.py
from django.http import HttpResponse, request,HttpResponseRedirect 
from django.urls import reverse
from django.shortcuts import render
from listings.models import Band, Listing
from listings.forms import BandForm, ContactUsForm, ListingForm
from django.core.mail import send_mail
from django.shortcuts import redirect # ajoutez cet import


def home(request):

    return HttpResponse('<h1>Bienvenue sur ma page!</h1>')

def band_list(request):
    bands = Band.objects.all()
    return render(request, "listings/band_list.html", {'bands': bands })

def band_detail(request, band_id): 
    # notez le paramètre id supplémentaire
    band = Band.objects.get(id=band_id)  # nous insérons cette ligne pour obtenir le Band avec cet id
    return render(request,
            'listings/band_detail.html',
            {'band': band}
    ) # nous mettons à jour cette ligne pour passer le groupe au gabarit
def band_create(request):
  
    if request.method == 'POST':
        form = BandForm(request.POST)
        
        if form.is_valid():
            # créer une nouvelle « Band » et la sauvegarder dans la db
            band = form.save()
            """ redirige vers la page de détail du groupe que nous venons de créer
                nous pouvons fournir les arguments du motif url comme arguments à la fonction de redirection
            """
            return redirect('band-detail', band.id)
    else:
        form = BandForm()
    return render(request,
            'listings/band_create.html',
            { 'form': form}
    )

def band_update(request, id):
    band= Band.objects.get(id=id)
    # on pré-remplir le formulaire avec un groupe existant ,par largument d'instance
    #form = BandForm(instance=band)
    if request.method == 'POST':
        form = BandForm(request.POST, instance=band)
        if form.is_valid():
            # mettre à jour le groupe existant dans la base de données
            band = form.save()
            # rediriger vers la page détaillée du groupe que nous venons de mettre à jour
            return redirect('band-detail', band.id)
    else:
        # on pré-remplir le formulaire avec un groupe existant ,par largument d'instance
        form = BandForm(instance=band)
    return render(request,
                'listings/band_update.html',
                {'form': form}
    )

def band_delete(request, id):
    band= Band.objects.get(id=id)
    if request.method == 'POST':
        # supprimer le groupe de la base de données
        band.delete()
        # rediriger vers la liste des groupes
        return redirect('band-list')

    # pas besoin de « else » ici. Si c'est une demande GET, continuez simplement
    return render(request,
            'listings/band_delete.html',
            {'band': band})
            
def listing_create(request):
    if request.method == 'POST':
        form = ListingForm(request.POST)
        #validation
        if form.is_valid():
            #enregistrement
            listing = form.save()
            return redirect('listing-detail', listing.id)
    else:
        form = ListingForm()
    return  render(request,
            'listings/listing_create.html',
            { 'form': form})

def listing_list(request):
    listings = Listing.objects.all()
    return render(request, "listings/listing_list.html", {'listings': listings })

def listing_detail(request, listing_id):  # notez le paramètre id supplémentaire
    #print("la listing key:", listing_id)
    listing = Listing.objects.get(id=listing_id)  # nous insérons cette ligne pour obtenir le Band avec cet id
    return render(request,
            'listings/listing_detail.html',
            {'listing': listing}
    ) # nous mettons à jour cette ligne pour passer le groupe au gabarit
def listing_detail_annonce(request, listing_an_id):
    listing_annonce = Listing.objects.get(id=listing_an_id) 
    return render(request,
        'listings/listing_detail.html',
            {'listing_annonce': listing_annonce}
     )

def contact(request):
    if request.method == 'POST':
        # créer une instance de notre formulaire et le remplir avec les données POST
        form = ContactUsForm(request.POST)
        if form.is_valid():
            send_mail(
            subject=f'Message from {form.cleaned_data["name"] or "anonyme"} via MerchEx Contact Us form',
            message=form.cleaned_data['message'],
            from_email=form.cleaned_data['email'],
            recipient_list=['admin@merchex.xyz'],
        )
        return redirect("send-eamil")
        # si le formulaire n'est pas valide, nous laissons l'exécution continuer jusqu'au return
        # ci-dessous et afficher à nouveau le formulaire (avec des erreurs).
    else:
        # ceci doit être une requête GET, donc créer un formulaire vide : ', request.POST)

        form = ContactUsForm() # ceci doit être une requête GET, donc créer un formulaire vide
    return render(request,
        'listings/contact.html',
        {'form': form})  # passe ce formulaire au gabarit


def about(request):
    return HttpResponse('<h1>À propos</h1> <p>Nous adorons merch !</p>')

def help(request):
    return HttpResponse("<h1>Bienvenue sur ma page d'aide!</h1>")

merchex/listings/templates/listings/band_create.html
{% extends 'listings/base.html' %}

{% block content %}

<h1>Créer un nouveau groupe</h1>
<!-- novalidate permet de desactiver la validation coté clien --> 
    <form action="" method="post" >
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Envoyer">
    </form>

{% endblock content %}

merchex/listings/templates/listings/band_delete.html
{% extends 'listings/base.html' %}

{% block content %}

<h1>Supprimer le groupe</h1>


<p>Etes-vous sûr de vouloir supprimer le groupe : {{ band.name }} ?</p>
<form action="" method="post">
    {% csrf_token %}
    
    <input type="submit" value="Supprimer">
</form>

{% endblock content %}

merchex/listings/templates/listings/band_detail.html
{% extends 'listings/base.html' %}

{% block content %}
    <h2>{{ band.name }}</h2>

    <ul>
        {% comment %} Django a ajouté la méthode get_genre_display pour convertir les valeurs de la base de données genre 
        dans leur format d'affichage (par exemple Hip Hop ). {% endcomment %}
        <li>Genre : {{ band.get_genre_display  }}</li>
        <li>Année de formation : {{ band.year_formed }}</li>
        <li>Actif : {{ band.active|yesno }}</li>
        {% if band.official_homepage %}
        <li>
            <a href="{{ band.official_homepage }}">{{ band.official_homepage }}</a>
        </li>
        {% endif %}
    </ul>

    <p>{{ band.biography }}</p>
    <a href="{% url 'band-update' band.id %}">modifier un groupes</a>
    <a href="{% url 'band-delete' band.id %}">Supprimer un  groupe</a>
    <a href="{% url 'band-list' %}">Retour à la des groupes</a>
   
{% endblock content %}

merchex/listings/templates/listings/band_list.html
{% extends 'listings/base.html' %}

{% block content %}
        <h1>Hello Django !</h1>

        <a href="{% url 'band-create' %}">Créer un nouveau groupe</a>

        <p>Mes groupes préférés sont :</p>
        <!-- TODO : liste des groupes -->
        <ul>
            {% for band in bands %}
            
                {% if band.name %}
                <li>
                    <a href="{% url 'band-detail' band.id %}">{{ band.name|upper }}</a>
                    - <a href="{% url 'band-update' band.id %}">[modifier]</a>
                </li>
                {% endif %}
                {% for listing in band.listing_set.all %}
        <ul>
            <li><a href="{% url 'listing-detail' band.id %}">{{ listing }}</a></li>
        </ul>
        {% endfor %}
            {% endfor %}
        </ul>
        
{% endblock content %}

merchex/listings/templates/listings/band_update.html
{% extends 'listings/base.html' %}

{% block content %}
  <h1>Mise à jour du groupe</h1>

  <form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Envoyer">
 </form>
 
 {% endblock content %}

merchex/listings/templates/listings/base.html
{% load static %}

<html>
    <head>
        <title>Merchex</title>
        <link rel="stylesheet" href="{% static 'listings/styles.css' %}" />
    </head>
    <body>
        <nav>
            <a href="{% url 'band-list' %}">Groupes</a>
            <a href="{% url 'listing-list' %}">Listes</a>
            <a href="{% url 'listing-list' %}">À propos de nous</a>
            <a href="{% url 'listing-list' %}">Contactez-nous</a>
        </nav>
        {% block content %}
        {% endblock content %}

    </body>
</html>

merchex/listings/templates/listings/contact.html
{% extends 'listings/base.html' %}

{% block content %}

<h1>Contactez-nous!</h1>
<p>Nous sommes là pour vous aider.</p>

<form action="" method="POST" >
{% csrf_token %}
{{ form.as_p }}
<input type="submit" value="Envoyer">
</form>

{% endblock content %}

merchex/listings/templates/listings/listing_create.html
{% extends 'listings/base.html' %}

{% block content %}

<h1>Create new Listing</h1>
<!-- novalidate permet de desactiver la validation coté client --> 
    <form action="" method="post" >
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Envoyer">
    </form>

{% endblock content %}

merchex/listings/templates/listings/listing_detail.html
{% extends 'listings/base.html' %}

{% block content %}
    {% if listing_annonce %}
        <h2>{{ listing_annonce.title }}</h2>


        <ul>
            {% comment %} Django a ajouté la méthode get_genre_display pour convertir les valeurs de la base de données genre 
            dans leur format d'affichage (par exemple Hip Hop ). {% endcomment %}
            <li>description : {{ listing_annonce.description  }}</li>
            <li>Année de sortie: {{ listing_annonce.year }}</li>
            <li>Sold : {{ listing_annonce.sold|yesno }}</li>
            {% if listing_annonce.offtypesicial_homepage %}
            <li>
                <a href="{{ listing_annonce.band.name }}">{{ listing_annonce.band.name  }}</a>
            </li>
            {% endif %}
        </ul>
    {% else %}
        <h2>{{ listing.title }}</h2>
    
    <ul>
        {% comment %} Django a ajouté la méthode get_genre_display pour convertir les valeurs de la base de données genre 
        dans leur format d'affichage (par exemple Hip Hop ). {% endcomment %}
        <li>description : {{ listing.description  }}</li>
        <li>Année de sortie: {{ listing.year }}</li>
        <li>Sold : {{ listing.sold|yesno }}</li>
        {% if listing.offtypesicial_homepage %}
        <li>
            <a href="{{ listing.band.name }}">{{ listing.band.name  }}</a>
        </li>
        {% endif %}
    </ul>
    {% endif %}
    
    <a href="{% url 'listing-list' %}">Retour à tous les listings</a>
{% endblock content %}

merchex/listings/templates/listings/listing_list.html
{% extends 'listings/base.html' %}

{% block content %}
        <h1>Hello Django !</h1>
        <a href="{% url 'listing-create' %}">Create new listing</a>
        <p>Mes listes préférées sont :</p>
        <!-- TODO : liste des groupes -->
        <ul>
            {% for listing in listings %}
            
                {% if listing.title %}
                <li><a href="{% url 'listing-detail' listing.id %}">{{ listing.title|upper }}</a></li>
                {% endif %}
                
            {% endfor %}
        </ul>

{% endblock %}